---
deployment:
  tasks:
    - cp .env.live .env
    - export DEPLOYPATH=/home/koboon1q/demo.planeat.app
    - cp -r /. $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan down
    - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
    - php artisan migrate --force
    - php artisan cache:clear
    - php artisan auth:clear-resets
    - php artisan route:clear
    - php artisan route:cache
    - php artisan config:clear
    - php artisan config:cache
    - php artisan up
