---
deployment:
  tasks:
    - cp .env.live .env
    - export DEPLOYPATH=/home/koboon1q/demo.planeat.app
    - rsync -av --progress . $DEPLOYPATH --exclude .git
    - cd $DEPLOYPATH
    - php artisan down
    - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
    - php artisan migrate --force
    - php artisan up
    - php artisan inspire
